com.spotify.Client.json
The old version no longer being possible to download:
```
x10an14@x10-HomeDesktop ~ $ date && lsb_release -a && uname -a
Wed Dec 13 20:23:55 CET 2017
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia
Linux x10-HomeDesktop 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
x10an14@x10-HomeDesktop ~ $ flatpak install flathub com.spotify.Client stable
Installing: com.spotify.Client/x86_64/stable from flathub
[#=                  ] Downloading: 0 bytes/90,7 MB
error: While downloading https://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.67.582.g19436fa3-28_amd64.deb: Server returned status 404: Not Found
x10an14@x10-HomeDesktop ~ $ …
```
=> Update to a version possible to download

com.spotify.Client.appdata.xml
I saw you updated the Spotify appdata file to add the description but the webapp still says "No description available". I've investigated a little and the appstream.xml file provided by flatpak doesn't include the tag <description> for this app. 
I think this is because the description text you provided is not inside a <p> tag. Other apps have <description><p>This app blah blah...</p></description>
=> Enclose description data with <p></p>

com.spotify.Client.json
Currently used nss is a year old. Newest nss successfully work with spotify on Archlinux.
=> Update nss lib

spotify-bin
Spotify app accepts several arguments which are corectly passed from .dekstop file but ignored by shell script. This change pass them in shell script as well. Example:
`com.spotify.Client --show-console`
=> Allow passing arguments from launcher to spotify app

com.spotify.Client.appdata.xml, com.spotify.Client.json
Spotify seems to change its url to fetch the client with every update. This bugfix worked for me.
=> Bugfix Error 404 while fetching Spotify

com.spotify.Client.json
When looking inside official spotify deb you can see that it recommends libavcodec-extra57 as latest among few older alternatives. This translates to ffmpeg 3.2.14 in debian (https://packages.debian.org/stretch/libavcodec-extra57) which means we can safely update to it.
Also use xz archive which is slightly smaller.
=> Update ffmpeg to 3.2.14

.gitmodules, com.spotify.Client.json, flathub.json
This drops electron base app in favor of shared-modules + gconf and libnotify.
The pros are that we don't depend on someone updating baseapp and also we can drop some unnecessary deps.
The cons are that we have to extend manifest however those should never see any updates so it won't be maintenance burden. We also have to build them on every spotify update but it won't take more than few minutes.
Also drop i386 arch which no longer exists.
Fixes https://github.com/flathub/com.spotify.Client/issues/91
=> Use freedesktop 19.08 runtime

spotify-bin
Adds env PULSE_PROP_application.icon_name="com.spotify.Client" to spotify-bin so that the correct icon is shown in pulseaudio settings.
=> Add PULSE_PROP_application.icon_name environment variable

com.spotify.Client.json, update-release.py
https mirror is very unreliable recently so switch to http for the rescue.
Fixes https://github.com/flathub/com.spotify.Client/issues/108
=> Switch to http source

com.spotify.Client.json
This is still going to require some testing to make sure there are no issues with compatibility or regressions.
Lets see how far up in the versions we can get before it breaks.
=> Update to the latest version of FFmpeg that will still play local files

com.spotify.Client.desktop, com.spotify.Client.json
This commit adds com.spotify.Client.desktop and uses that for the base of the .desktop file instead of the upstream .desktop file.
=> Replace upstream .desktop file

com.spotify.Client.desktop
Gnome provides a settings menu for permitting/disabling access to the notification daemon.
In order for an application to show up its application file needs to expose X-GNOME-UsesNotifications=true
This should get Spotify to show up in the notification settings under Gnome.
You can read more on this here: https://wiki.gnome.org/Initiatives/GnomeGoals/NotificationSource
=> Expose the app to Gnome's notification controls

com.spotify.Client.json
Also remove python-six as it's provided in the runtime and bump shared-modules
=> runtime: update to 20.08

com.spotify.Client.json, spotify-bin
Baby's first flathub contribution! (In case it's unclear, I'm baby.)
I thought that my first attempt at adding spotifywm was gonna fall flat on its face and I was gonna have to spend a couple hours fixing something, but it... just seems to work, exactly as I thought it would. I put the preload library in /app/lib, hope that's the right place semantically.
When I first tried to work on this, I struggled with the server not really cooperating with letting me download the base package but I was able to complete the build process today and test it, and it seems to be working as expected. This should fix #68, or at the very least, make it better. :)
=> Add spotifywm to fix window class, icon, etc.

com.spotify.Client.appdata.xml, com.spotify.Client.json
Spotify stopped releasing new deb packages therefore this switches to snap as extra-data source which is considered acceptable elsewhere in flathub.
This also enables update-checker support for making future updates easier.
As a bonus this may fix issues with unreliable downloads from spotify cdn.
Fixes https://github.com/flathub/com.spotify.Client/issues/145
=> Update to 1.1.46.916.g416cacf1 and use snap as source

com.spotify.Client.json
I've verified that local playback still works.
=> Update ffmpeg to version 3.4.8

com.spotify.Client.json
I believe none of these changes should break anything.
The x-checker will alert you about 6.0.2 but that requires a newer setuptool than given by the runtime, I can remove that if you want.
=> Update libraries, x-checker things

com.spotify.Client.json
This was removed by mistake in https://github.com/flathub/com.spotify.Client/commit/65b7c917a29ea43c150ada9838adf6a0653e1cb4
Fix #158
=> Add back xprop

com.spotify.Client.json
The recent versions fail to build due to missing deps which make it impossible to build and test new spotify releases. Auto updates makes sense for something which is effortless to update otherwise this will block app updates as a whole.
=> Remove x-checker-data for python modules

com.spotify.Client.json
#174 added lzo support to unsquashfs as snaps now use this, it was superseded by #175 but the lzo patches were not picked up. Add the lzo patches so the Flatpak is installable once more. Fixes #176. Thanks to @Erick555
=> pick lzo patches from #174

com.spotify.Client.json
For some reason, when the icons folder is missing, the title bar comes up empty. 
I don't know why, but this fixes the issue.
This resolves #184 
Edit: I think this also resolves #180 and #179. I didn't mention them previously because I didn't notice them before I made the change.
=> Fix title bar coming up empty

com.spotify.Client.json
Hello,
Currently `apply_extra` is not silent when performing the unsquashfs, as I undestand this is not desirable by flatpak conventions.
1. The first commit in this PR is to add the `-quiet` flag so that installs don't break the cli output of flatpak.
2. Next I also simplified the `apply_extra` process so that it only extract the required files from the `.snap` file (so `usr/lib` is not extracted and deleted).
3. Finally unified/simplified all `mv`/`rm` commands into one of each.
I tested it locally and the final `extra` folder contents and structure is exactly the same as is currently being, but faster and quieter.
In case that only the first part, or the first 2 parts are desired, tell me so I can remove the changes not desired from this PR.
=> Silent install

com.spotify.Client.appdata.xml, com.spotify.Client.json
This PR takes the commit from #259 and cherry-picks https://github.com/eclipseo/com.spotify.Client/commit/f0b705d509a3ab863d9da3c8c20da253c88d8014 with removed references to beta/edge - leaving what's (most likely) necessary to get the appindicator support. 
The build from flathubbot now works for me. I can also tell that the MPRIS support on Wayland must be much better - I've tested this with KDE Connect's "Pause media during calls". It works wonders - pauses Spotify when the call is incoming and starts it back again when the call is finished.
=> Update spotify.snap to 1.2.22.982.g794acc0a

com.spotify.Client.json, ffmpeg-binutils-2.41.patch
Updating to 23.08 results in the ffmpeg build to fail. 
So looking at https://github.com/flathub/org.blender.Blender/pull/154 adding the build option "--disable-inline-asm" did build ffmpeg successfully. 
After testing Local Files Playback, everything seems to be working fine.
=> Update runtime to 23.08 & ffmpeg patch

spotify-bin
This workaround is only necessary to make proxy settings persist when users are not logged in (i.e., when they launch the app for the first time).
See issue #280 for more context on this.
Closes #280
=> Workaround: Create "spotify" directory in $XDG_CONFIG_HOME

com.spotify.Client.json
Seemingly not a problem on KDE, but cursor is still small on GNOME hosts.
Fixes: #306
=> Set XCURSOR_PATH for running Spotify under Wayland

spotify-bin
This causes the window to be cropped when running under Wayland, also don't need it anyways since under Wayland the window will always have proper scaling.
=> Only pass force-device-scale-factor if running in XWayland
