- com.spotify.Client.json
Sorry about that - was a bit too quick & eager...
> Bugfix: Remember to specify correct file sizes..

- com.spotify.Client.json
Spotify updated package
-fixed url
-new checksums
-sizes
> newer client version

- com.spotify.Client.json
The previous version was no longer accessible.
> Update version to 1.0.72.117.g6bd7cc73-35

- com.spotify.Client.json
- spotify-bin
- xsettings.py
Use a python xsettings client to read the display scaling factor before
launching Spotify, to be able to launch it with the correct scale
factor.
> Automatically detect HiDpi displays

- com.spotify.Client.json
There were couple security vulns: https://curl.haxx.se/docs/vuln-7.59.0.html
Other changes: https://curl.haxx.se/changes.html#7_61_0
> Use curl from runtime

- com.spotify.Client.appdata.xml
- com.spotify.Client.json
They were very nice this time and didn't remove the previous  version.
> Update to 1.0.96.181.gf6bc1b6b-12

- com.spotify.Client.json
I would think this would be pretty safe.
> Update to the latest version of xprop

- com.spotify.Client.json
- set-dark-theme-variant.py
- spotify-bin
Detect when the Spotify window shows up.
> Detect the Spotify window

- com.spotify.Client.appdata.xml
- com.spotify.Client.json
This isn't listed in deb repos but snap use it already: https://snapcraft.io/spotify
> Update to 1.1.10.546.ge08ef575-19

- com.spotify.Client.appdata.xml
- com.spotify.Client.json
This version is used in official snap: https://snapcraft.io/spotify
> Update to 1.1.42.622

- com.spotify.Client.json
> Remove gtk2 dependency

- com.spotify.Client.json
Also:
- Updated ffmpeg to 4.1.7
- Updated spotifywm to the latest commit
- Updated shared-modules
> Updated runtime to 21.08 and others

- com.spotify.Client.json
Small patch to update flatpak's runtime and shared modules to the latest version
> Update Runtime and shared modules

- com.spotify.Client.json
- ffmpeg-patch.patch
> Add ffmpeg 4.4 and sdl2 (needed to compile ffmpeg) to fix local files.

- xsettings.py
Closes #215
Waiting response from creator of #215 to ensure that this fixes the issue
EDIT: This appears to fix the issue.
> Update xsettings.py to the latest version from the developer.

- com.spotify.Client.json
- spotifywm-patch.patch
[dasJ/spotifywm](https://github.com/dasJ/spotifywm) does not work anymore, after various Spotify updates. Instead, [amurzeau/spotifywm](https://github.com/amurzeau/spotifywm) works just fine. This is mostly temporary until the main developer merges the pull request.
> Update `spotifywm` from `amurzeau/spotifywm`

- com.spotify.Client.json
> Use patchelf to satisfy curl-gnutls dependency instead of symlink

- com.spotify.Client.appdata.xml
- com.spotify.Client.json
- flathub.json
Closes https://github.com/flathub/com.spotify.Client/pull/259
Closes https://github.com/flathub/com.spotify.Client/pull/260
Closes https://github.com/flathub/com.spotify.Client/issues/257
> Update spotify.snap to 1.2.22.982.g794acc0a (+ some fixes)

- README.md
- spotify-bin
https://aur.archlinux.org/cgit/aur.git/tree/spotify.sh?h=spotify
> Add custom flags

- spotify-bin
- Explicitly use bash
- Modernize notation
> Minor fixes for spotify-bin script
